name: Gatling Load Test

on:
  workflow_dispatch:
  push:
    branches: [ load-test ]
  pull_request:
    branches: [ load-test ]

jobs:
  gatling:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download Gatling
        run: |
          wget https://github.com/gatling/gatling/releases/download/3.11.3/gatling-charts-highcharts-bundle-3.11.3-bundle.zip
          unzip gatling-charts-highcharts-bundle-3.11.3-bundle.zip

      - name: Run Gatling Simulation
        run: |
          ./gatling-charts-highcharts-bundle-3.11.3/bin/gatling.sh -s computoyoursimulation.SimulationClassName
        env:
          JAVA_OPTS: "-DbaseUrl=http://localhost:8080"

      - name: Upload Gatling reports
        uses: actions/upload-artifact@v4
        with:
          name: gatling-report
          path: gatling-charts-highcharts-bundle-3.11.3/results/
