name: k6 Load Test

on:
  workflow_dispatch:
  push:
    branches: [load-test]
  pull_request:
    branches: [load-test]

jobs:
  k6:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Build Spring Boot app
        run: ./gradlew clean build

      - name: Start app and Run Test
        run: |
          java -jar build/libs/itemservice-0.0.1-SNAPSHOT.jar --server.address=0.0.0.0 > spring.log 2>&1 &
          for i in {1..30}; do
            curl -sf http://localhost:8080/items && echo "READY" && exit 0
            echo "Waiting for app..."
            sleep 5
          done
          echo "App NOT available" && exit 1
          k6 run loadtest.js
          cat spring.log
