name: k6 Load Test

on:
  workflow_dispatch:
  push:
    branches: [load-test]
  pull_request:
    branches: [load-test]

jobs:
  k6:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Build Spring Boot app
        run: ./gradlew clean build

      - name: Start Spring Boot app
        run: |
          java -jar build/libs/itemservice-0.0.1-SNAPSHOT.jar --server.address=0.0.0.0 > spring.log 2>&1 &
          # Installa k6
          sudo apt-get update && sudo apt-get install -y gnupg2
          curl -s https://dl.k6.io/key.gpg | sudo apt-key add -
          echo "deb https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update && sudo apt-get install -y k6
          # Attendi che l'app sia pronta
          for i in {1..30}; do
            curl -sf http://localhost:8080/items && echo "READY" && break
            echo "Waiting for app..."
            sleep 5
          done
          # Esegui il test k6
          k6 run loadtest.js
          cat spring.log

      #- name: Wait for Spring Boot to be ready
      #  run: |
      #    for i in {1..30}; do
      #      curl -sf http://localhost:8080/items && echo "READY" && exit 0
      #      echo "Waiting for app..."
      #      sleep 5
      #    done
      #    echo "App NOT available" && exit 1

      #- name: Run k6 load test
      #  uses: grafana/k6-action@v0.3.1
      #  with:
      #    filename: loadtest.js
